name: wisatabumnag
description: Wisata Pulau Setan
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  ai_barcode_scanner: ^6.0.1
  alice: ^1.0.0-dev.11
  alice_dio: ^1.0.6
  bloc: ^9.0.0
  bloc_concurrency: ^0.3.0
  bubble_tab_indicator: ^0.1.6
  cached_network_image: ^3.2.2
  card_swiper: ^3.0.1
  change_case: ^2.2.0
  collection: ^1.16.0
  connectivity_plus: ^6.1.4
  crypto: ^3.0.2
  dartz: ^0.10.1
  device_info_plus: ^11.5.0
  dio: ^5.8.0+1
  dotted_border: ^3.0.1
  equatable: ^2.0.3
  firebase_core: ^3.14.0
  firebase_messaging: ^15.2.7
  firebase_remote_config: ^5.4.5
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_hooks: ^0.21.2
  flutter_libphonenumber: ^2.5.1
  flutter_local_notifications: ^17.2.4
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.2.7
  flutter_rating_bar: ^4.0.1
  flutter_screenutil: ^5.5.3+2
  flutter_staggered_grid_view: ^0.7.0
  flutter_svg: ^2.2.0
  formz: ^0.8.0
  freezed_annotation: ^3.0.0
  geolocator: ^14.0.1
  get_it: ^8.0.3
  go_router: ^15.2.4
  google_fonts: ^6.2.1
  google_geocoding_api: ^1.0.1+2
  google_maps_flutter: ^2.2.1
  image_cropper: ^9.1.0
  image_picker: ^1.1.2
  injectable: ^2.5.0
  internet_connection_checker: ^3.0.1
  intl: ^0.20.2
  json_annotation: ^4.9.0
  lottie: ^3.3.1
  maps_launcher: ^3.0.0+1
  pretty_dio_logger: ^1.1.1
  pull_to_refresh: ^2.0.0
  readmore: ^3.0.0
  retrofit: ^4.4.2
  rxdart: ^0.28.0
  shared_preferences: ^2.0.15
  syncfusion_flutter_datepicker: ^30.1.37
  tab_indicator_styler: ^2.0.0
  url_launcher: ^6.1.6
  uuid: ^4.5.1
  webview_flutter: ^4.13.0

dev_dependencies:
  bloc_test: ^10.0.0
  build_runner: ^2.5.4
  flutter_gen_runner: ^5.10.0
  flutter_launcher_icons: ^0.14.4
  flutter_test:
    sdk: flutter
  freezed: ^3.0.6
  injectable_generator: ^2.7.0
  json_serializable: ^6.9.5
  mocktail: ^1.0.4
  retrofit_generator: ^9.2.0
  very_good_analysis: ^9.0.0

flutter_gen:
  output: lib/gen/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)

  # Optional
  integrations:
    flutter_svg: true
    # flare_flutter: true
    # rive: true
    lottie: true

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/animations/
    - assets/fonts/
    - assets/google_fonts/
    - assets/icons/
    - assets/images/
    - assets/images/logo/
    - assets/jsons/
