name: wisatabumnag
description: Wisata Pulau Sultan
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: 3.0.5

dependencies:
  bloc: ^8.1.0
  bloc_concurrency: ^0.2.0
  bubble_tab_indicator: ^0.1.6
  cached_network_image: ^3.2.2
  card_swiper: ^2.0.4
  change_case: ^1.0.2
  collection: ^1.16.0
  connectivity_plus: ^2.3.9
  crypto: ^3.0.2
  dartz: ^0.10.1
  device_info_plus: ^5.0.5
  dio: ^4.0.6
  equatable: ^2.0.3
  firebase_core: ^2.1.0
  firebase_remote_config: ^3.0.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_hooks: ^0.18.5+1
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.2.7
  flutter_screenutil: ^5.5.3+2
  flutter_svg: ^1.1.5
  formz: ^0.5.0-dev.1
  freezed_annotation: ^2.1.0
  geolocator: ^9.0.2
  go_router: ^5.0.5
  google_fonts: ^3.0.1
  google_geocoding_api: ^1.0.1+2
  google_maps_flutter: ^2.2.1
  image_picker: ^0.8.6
  injectable: ^1.5.3
  internet_connection_checker: ^1.0.0+1
  intl: ^0.17.0
  json_annotation: ^4.7.0
  lottie: ^2.0.0
  maps_launcher: ^2.0.1
  pretty_dio_logger: ^1.1.1
  readmore: ^2.2.0
  retrofit: ^3.3.1
  rxdart: ^0.27.5
  shared_preferences: ^2.0.15
  syncfusion_flutter_datepicker: ^20.3.56
  tab_indicator_styler: ^2.0.0
  url_launcher: ^6.1.6
  uuid: ^3.0.6
  webview_flutter: ^3.0.4

dev_dependencies:
  bloc_test: ^9.0.3
  build_runner: ^2.2.0
  flutter_gen_runner: ^5.0.1
  flutter_launcher_icons: ^0.10.0
  flutter_test:
    sdk: flutter
  freezed: ^2.1.0+1
  get_it: ^7.2.0
  injectable_generator: ^1.5.4
  json_serializable: ^6.3.1
  mocktail: ^0.3.0
  retrofit_generator: ^4.2.0
  very_good_analysis: ^3.0.1

flutter_gen:
  output: lib/gen/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)

  # Optional
  integrations:
    flutter_svg: true
    # flare_flutter: true
    # rive: true
    lottie: true

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/animations/
    - assets/fonts/
    - assets/google_fonts/
    - assets/icons/
    - assets/images/
    - assets/images/logo/
    - assets/jsons/
